- src/components/IgnoranceCoinsDisplay/IgnorancePremiumIcons.tsx
- src/components/NavigationComponents/NavActions.tsx
- src/components/NavigationComponents/NavIcon.tsx
- src/components/NavigationComponents/NavSoundtrackIcon.tsx
- src/components/Quiz/DailyQuiz.tsx
- src/components/Quiz/FinalChallengeQuiz.tsx
- src/components/Quiz/FinalChallengeQuizModal.tsx
- src/components/Quiz/ModuleQuizV2.tsx
- src/components/StampIcon.tsx
- src/components/VideoBackground.tsx
- src/components/modals/ModuleModalV2.tsx
- src/components/modals/ProfileModal/ProgressionStatusModal/ProgressionStatusModal.tsx
- src/components/modals/VideoModal.tsx
- src/hooks/index.ts
- src/hooks/useSoundtrack.tsx
- src/hooks/useTrail.tsx
- src/pages/MainPage.tsx
- src/pages/Trail.tsx
- src/recoil/trailRecoilState.ts
- src/routes.tsx
- src/services/TrailServices.ts
- src/services/UserServices.ts
- src/services/module.ts
- src/utils/constants/constants.ts
- src/utils/constants/mouseOverConstants.ts
- src/utils/scripts/finalChallenge/FinalChallengeScript.ts
- Refatoração das trilhas
- Correção do bug de vídeo assistido
> v2.0.0-beta

- src/components/BaboonHelp.tsx
- src/components/Oracle/OracleChat/components/OracleAnimation.tsx
- src/components/modals/UnlockAnimation.tsx
- src/utils/algorithms/webmToMov.ts
- src/utils/constants/constants.ts
- [] Feature
- [] Bug
**Link**
> fix: Correção das animações do Safari

- src/components/modals/Tutorial/TutorialModal.tsx
- src/components/modals/Tutorial/components/TutorialContent.tsx
- src/components/modals/Tutorial/components/TutorialTopics.tsx
- [] Feature
- [] Bug
**Link**
> fix: Correção do ícone de tópico de tutorial

- src/components/modals/Tutorial/TutorialModal.tsx
- src/components/modals/Tutorial/components/TutorialContent.tsx
- src/components/modals/Tutorial/components/TutorialTopics.tsx
- Correção do ícone do tópico de tutorial
> v2.0.2-beta

- src/components/IgnoranceCoinsDisplay/IgnorancePremiumIcons.tsx
- src/components/Quiz/ModuleQuizV2.tsx
- src/components/modals/UnlockAnimation.tsx
- src/pages/Trail.tsx
- src/recoil/trailRecoilState.ts
- [] Feature
- [] Bug
**Link**
> feat: Adição da posição dinâmica dos módulos e ajustes no Oráculo

- src/components/modals/VideoModal.tsx
- [] Feature
- [] Bug
**Link**
> Feat: Adição do checkbox para marcar vídeo como concluído

- src/components/modals/Narrative/DefaultNarrativeModal.tsx
- src/services/analytics.ts
- [] Feature
- [] Bug
**Link**
> Feat: Adição do Analytics para a narrativa

- src/components/BaboonHelp.tsx
- src/components/IgnoranceCoinsDisplay/IgnorancePremiumIcons.tsx
- src/components/Oracle/OracleChat/OracleChat.tsx
- src/components/Oracle/OracleChat/components/CollapseQuestions.tsx
- src/components/Oracle/OracleChat/components/OracleInput.tsx
- src/components/Oracle/OracleHeader.tsx
- src/components/Quiz/ModuleQuizV2.tsx
- src/pages/CheetahPath.tsx
- src/pages/Oracle.tsx
- src/pages/Trail.tsx
- src/recoil/trailRecoilState.ts
- src/utils/constants/mouseOverConstants.ts
- [] Feature
- [] Bug
**Link**
> Feat: Remoção das Limitações do Oráculo

- .github/workflows/s3-deploy.yml
- src/components/modals/Narrative/DefaultNarrativeModal.tsx
- src/components/modals/ShopModal/ShopModal.tsx
- src/services/analytics.ts
- Remoção dos tokens do oráculo da loja
- Correção do Analytics
> v2.2.1-beta

- src/components/LoginRegister.tsx
- src/components/NavigationComponents/styles/NavIcon.css
- src/components/styles/LoginRegister.css
- src/pages/ForgotPassword.tsx
- src/pages/Login.tsx
- src/pages/Register.tsx
- src/pages/ResetPassword.tsx
- src/pages/styles/ForgotPassword.css
- src/pages/styles/Login.css
- src/pages/styles/Register.css
- src/pages/styles/ResetPassword.css
- [] Bug
**Link**
https://github.com/user-attachments/assets/9ae3ae1f-5119-497e-ab99-ce0c6420f5be
> feat: RESPONSIVIDADE - Criação das páginas de login/cadastro/esqueci senha responsivas

- src/components/VideoBackground.tsx
- src/pages/Trail.tsx
- Correção na atualização da animação na trilha
> v2.2.3-beta

- src/components/modals/ShopModal/ShopModal.tsx
- src/components/modals/ShopModal/components/ShopItemDetailed.tsx
- src/components/modals/ShopModal/components/ShopQuickFilter.tsx
- src/components/modals/ShopModal/components/styles/ShopItemDetailed.css
- src/components/modals/ShopModal/styles/ShopModal.css
- [] Bug
**Link**
https://github.com/user-attachments/assets/a4533179-b79e-4308-9cd4-17287c9ca19a
> Feat: RESPONSIVIDADE - Refatoração da loja responsiva

- src/components/modals/InventoryModal/InventoryModal.tsx
- src/components/modals/InventoryModal/components/InventoryItemDetailed.tsx
- src/components/modals/InventoryModal/components/styles/InventoryIteDetailed.css
- src/components/modals/InventoryModal/styles/InventoryModal.css
- src/components/modals/ShopModal/components/ShopQuickFilter.tsx
- [] Bug
**Link**
https://github.com/user-attachments/assets/b626ddb5-5cc9-490b-bb13-5a9c36e3885d
> Feat: RESPONSIVIDADE - Criação do inventorio responsivo

- src/components/IgnoranceCoinsDisplay/CoinsDisplay.tsx
- src/components/IgnoranceCoinsDisplay/IgnoranceProgress.tsx
- src/components/NavigationComponents/MobileNavIcon.tsx
- src/components/PerfilModalButton.tsx
- src/components/UserAvatar.tsx
- src/components/modals/ProfileModal/ProfileDataModal.tsx
- src/components/modals/ProfileModal/ProfileModal.tsx
- src/components/modals/ProfileModal/ProgressionStatusModal/ProgressionStatusModal.tsx
- src/components/modals/ProfileModal/ProgressionStatusModal/styles/ProgressionStatusModal.css
- src/components/modals/ProfileModal/styles/ProfileDataModal.css
- src/components/modals/ProfileModal/styles/ProfileModal.css
- src/components/styles/PerfilModalButton.css
- [] Bug
**Link**
https://github.com/user-attachments/assets/f20d23e2-8600-4204-ac9f-da2ad67f1834
> feat: RESPONSIVITY - profile modal

- src/components/NavigationComponents/MobileNavIcon.tsx
- src/components/modals/Narrative/DefaultNarrativeModal.tsx
- src/components/modals/Narrative/styles/DefaultNarrativeModal.css
- src/components/modals/SliderModal.tsx
- src/components/modals/styles/SliderModal.css
- src/config/dev.ts
- src/pages/styles/MainPage.css
- src/utils/animations/SplitText.js
- src/utils/animations/SplitTitle.js
- src/utils/animations/styles/SplitText.css
- src/utils/animations/styles/SplitTitle.css
- [] Bug
**Link**
https://github.com/user-attachments/assets/6df0a2d1-c57c-4129-b77d-93b399fa704c
> Feat: RESPONSIVIDADE - responsividade dos oculos da ignorancia

- src/components/Quiz/QuizAlertModal.tsx
- src/components/Quiz/styles/QuizAlertModal.css
- src/components/modals/InventoryModal/styles/InventoryModal.css
- src/components/modals/ShopModal/styles/ShopModal.css
- [] Bug
**Link**
https://github.com/user-attachments/assets/07c3b886-c576-4294-b38b-e480a1431421
> Feat: RESPONSIVIDADE - Criação do banner para o desafio diario

- src/components/modals/ProfileModal/RelicComponents/Relics.tsx
- src/utils/algorithms/backgroundAnimation.ts
- src/utils/constants/constants.ts
- src/utils/enums/soundtrackEnums.ts
- [] Feature
- [] Bug
**Link**
> feat: mudança de links de arquivos

- src/components/modals/ProfileModal/RelicComponents/Relics.tsx
- src/utils/algorithms/backgroundAnimation.ts
- src/utils/constants/constants.ts
- src/utils/enums/soundtrackEnums.ts
- Subtituição de links de arquivos
> v2.2.4-beta

- src/components/NavigationComponents/MobileNavIcon.tsx
- src/components/Quiz/GenericQuizModal.tsx
- src/components/Quiz/styles/GenericQuizModal.css
- src/components/Quiz/styles/QuizAlertModal.css
- [] Bug
**Link**
https://github.com/user-attachments/assets/c686ff40-6f4d-4139-9273-ca0881edf1fb
> Feat: RESPONSIVIDADE - criação do quiz responsivo

- src/components/modals/ModuleModalV2.tsx
- src/components/modals/styles/ModuleModalV2.css
- [] Bug
**Link**
https://github.com/user-attachments/assets/284e739a-3553-472b-9ef5-124c8a0f7a3c
> Feat: RESPONSIVIDADE - modulo dos videos

- src/components/Quiz/styles/GenericQuizModal.css
- src/components/modals/ProfileModal/styles/ProfileModal.css
- src/components/modals/VideoModal.tsx
- src/components/modals/styles/ModuleModalV2.css
- src/components/modals/styles/VideoModal.css
- src/components/styles/LoginRegister.css
- src/hooks/useWindowSize.tsx
- src/pages/styles/MainPage.css
- src/routes.tsx
- [] Bug
**Link**
https://github.com/user-attachments/assets/a8bbf824-e5d3-4101-a3f4-bd003f81d63a
> Feat: RESPONSIVIDADE - Criação do video do modulo responsivel

- src/components/BaboonHelp.tsx
- src/components/Oracle/OracleChat/OracleChat.tsx
- src/components/Oracle/OracleChat/components/CollapseQuestions.tsx
- src/components/Oracle/OracleChat/components/OracleAnimation.tsx
- src/components/Oracle/OracleChat/components/OracleInput.tsx
- src/components/Oracle/OracleHeader.tsx
- src/components/modals/VideoModal.tsx
- src/components/styles/BaboonHelp.css
- src/hooks/useWindowSize.tsx
- src/pages/Oracle.tsx
- [] Bug
**Link**
https://github.com/user-attachments/assets/59472072-8338-47c9-bf9a-c371ec028ba0
> Feat: RESPONSIVIDADE - Adição do oraculo

- src/components/Quiz/ModuleQuizV2.tsx
- src/components/modals/ModuleModalV2.tsx
- [] Feature
- [] Bug
**Link**
> fix: Correção da aparição da narrativa

- src/components/BackButton.tsx
- src/components/HomeButton.tsx
- src/components/IgnoranceCoinsDisplay/CoinsDisplay.tsx
- src/components/IgnoranceCoinsDisplay/IgnorancePremiumIcons.tsx
- src/components/IgnoranceCoinsDisplay/IgnoranceProgress.tsx
- src/components/IgnoranceCoinsDisplay/StatusProgress.tsx
- src/components/NavigationComponents/NavIcon.tsx
- src/components/Oracle/OracleChat/components/OracleMessage.tsx
- src/components/TrailIcon.tsx
- src/components/modals/InventoryModal/components/InventoryItemDetailed.tsx
- src/components/modals/ModuleModalV2.tsx
- src/components/modals/ProfileModal/ProgressionStatusModal/ProgressionStatusModal.tsx
- src/components/modals/ProfileModal/RelicComponents/RelicInfoSlide.tsx
- src/components/modals/RandomRewardModal.tsx
- src/components/modals/ShopModal/components/ShopItemDetailed.tsx
- src/pages/CheetahPath.tsx
- src/pages/Trail.tsx
> Feat: RESPONSIVIDADE - Desativa o tooltip quando está em mobile

- src/components/Oracle/OracleChat/components/CollapseQuestions.tsx
- src/pages/Oracle.tsx
- [] Feature
- [] Bug
**Link**
> Fixed: RESPONSIVIDADE - Correção da altura do oraculo

- src/components/modals/InventoryModal/InventoryModal.tsx
- src/hooks/useOwnedItems.tsx
- src/pages/CertificateDisplay.tsx
- src/routes.tsx
- src/services/CertificateService.ts
- Repaginação dos certificados
> v2.4.0-beta

- package.json
- src/pages/CertificateDisplay.tsx
- src/services/CertificateService.ts
- [] Feature
- [] Bug
**Link**
> Correção do layout do certificado

- package.json
- src/pages/CertificateDisplay.tsx
- src/services/CertificateService.ts
- Correção do layout do certificado
> v.2.3.1-beta

- src/components/NavigationComponents/MobileNavIcon.tsx
- src/components/NavigationComponents/NavActions.tsx
- src/components/Quiz/FinalChallengeQuiz.tsx
- src/pages/Trail.tsx
- src/utils/scripts/finalChallenge/FinalChallengeScript.ts
- [] Feature
- [] Bug
**Link**
> Fix: Correção de erros com o certificado

- src/components/BaboonHelp.tsx
- Correção do modal de ajuda do babuíno
> v2.4.2-beta
